In [1]:
"""
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Script: Data filtering with python panda's
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Goal: Perform data analyses on data extracted from Movebank and extract it to CSV
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Steps : 
1) Import data set
2) Show data set
3) Filter data set
4) Export dataset
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Date   : 20191011
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Version: 0.0.3
Last Changes:
1) Added Export functionality
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Author: Pieter Lems
"""

"\nScript: Data filtering with python panda's\n\nScript: Data filtering with python panda's\n\nGoal: Perform data analyses on data extracted from Movebank and extract it to CSV\n\nSteps : \n1) Import data set\n2) Show data set\n3) Filter data set\n4) Export dataset\n\nDate   : 20191011\nVersion: 0.0.3\nLast Changes:\n1) Added Export functionality\n\n"

In [2]:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 0) Import the required modules or functions from modules.
import pandas as pd
# pandas is used to generate DataFrames from extracted data

In [5]:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 1) Import and Read the extracted dataset (in this case the file format is CSV)
Swedish_Crane_Dataframe = pd.read_csv("20191012_Data_Sets/Swedish_Crane.csv")

In [8]:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 2) Show the dataset 
Swedish_Crane_Dataframe

,event-id,visible,timestamp,location-long,location-lat,argos:altitude,gps:fix-type,gps:hdop,gps:vdop,ground-speed,heading,height-above-ellipsoid,tag-tech-spec,tag-voltage,sensor-type,individual-taxon-canonical-name,tag-local-identifier,individual-local-identifier,study-name
0,1154727247,True,2013-07-21 03:06:32.000,13.583908,57.503796,NaN,3,2.0,3.0,0.0000,NaN,193.0,NaN,4110.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
1,1154727246,True,2013-07-21 03:51:34.000,13.578312,57.504063,NaN,3,1.5,2.5,0.5144,NaN,194.0,NaN,4100.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
2,1154727245,True,2013-07-21 04:07:09.000,13.578205,57.504150,NaN,3,1.1,1.5,0.0000,NaN,199.0,NaN,4110.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
3,1154727244,True,2013-07-21 04:22:57.000,13.577142,57.504177,NaN,3,1.6,2.0,0.0000,NaN,194.0,NaN,4110.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
4,1154727243,True,2013-07-21 04:38:39.000,13.576754,57.504238,NaN,3,1.1,1.6,0.0000,NaN,192.0,NaN,4110.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123800,1184857334,True,2016-02-11 16:18:02.000,8.841672,52.646145,NaN,3,1.3,2.3,0.0000,NaN,34.0,NaN,3640.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
123801,1184857333,True,2016-02-11 16:23:44.000,8.841692,52.646160,NaN,3,1.0,1.7,0.0000,NaN,34.0,NaN,3630.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
123802,1184857332,True,2016-02-13 08:51:38.000,8.841772,52.646118,NaN,3,1.1,1.4,0.0000,NaN,31.0,NaN,3640.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
123803,1184857331,True,2016-02-13 09:07:14.000,8.841748,52.646114,NaN,3,1.0,1.2,0.0000,NaN,29.0,NaN,3670.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"
123804,1184857330,True,2016-02-13 09:22:43.000,8.841743,52.646114,NaN,3,1.1,1.4,0.0000,NaN,34.0,NaN,3680.0,gps,Grus grus,9381,9381,"GPS telemetry of Common Cranes, Sweden"

In [17]:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 3) Filter the dataset on the selected columns
Filtered_Swedish_Crane_Dataframe = Swedish_Crane_Dataframe[["event-id",
                                                           "timestamp",
                                                           "location-long",
                                                           "location-lat",
                                                           "ground-speed",
                                                           "heading",
                                                           "height-above-ellipsoid",
                                                           "tag-local-identifier"]]

In [18]:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 4)Show the filtered dataframe
Filtered_Swedish_Crane_Dataframe

,event-id,timestamp,location-long,location-lat,ground-speed,heading,height-above-ellipsoid,tag-local-identifier
0,1154727247,2013-07-21 03:06:32.000,13.583908,57.503796,0.0000,NaN,193.0,9381
1,1154727246,2013-07-21 03:51:34.000,13.578312,57.504063,0.5144,NaN,194.0,9381
2,1154727245,2013-07-21 04:07:09.000,13.578205,57.504150,0.0000,NaN,199.0,9381
3,1154727244,2013-07-21 04:22:57.000,13.577142,57.504177,0.0000,NaN,194.0,9381
4,1154727243,2013-07-21 04:38:39.000,13.576754,57.504238,0.0000,NaN,192.0,9381
...,...,...,...,...,...,...,...,...
123800,1184857334,2016-02-11 16:18:02.000,8.841672,52.646145,0.0000,NaN,34.0,9381
123801,1184857333,2016-02-11 16:23:44.000,8.841692,52.646160,0.0000,NaN,34.0,9381
123802,1184857332,2016-02-13 08:51:38.000,8.841772,52.646118,0.0000,NaN,31.0,9381
123803,1184857331,2016-02-13 09:07:14.000,8.841748,52.646114,0.0000,NaN,29.0,9381
123804,1184857330,2016-02-13 09:22:43.000,8.841743,52.646114,0.0000,NaN,34.0,9381

In [21]:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# 4)Export the filtered dataframe to a CSV file called "FILTERED_Swedish_Crane.csv"
# The variable index = None makes sure no index is added at on each row
# The variable header=True makes sure the column names are added to the CSV file 
Filtered_Swedish_Crane_Dataframe.to_csv("20191012_Data_Sets/FILTERED_Swedish_Crane.csv",index=None,header=True)